Bugfix positioning
ohrimovich/donut-masterclass pull request #26
Opened 2021-05-17 12:40 UTC by grytsayo

Marging deleted

2021-05-17 14:44 UTC, ohrimovich requested changes
що це за зміни в файлі package-lock.json ?
І два зайвих файла main,css
main.css.map
Передивись виправ 
зроби коміи

2021-05-18 08:11 UTC, ohrimovich requested changes

2021-05-18 08:11 UTC, ohrimovich commented on src/sass/_about-us.scss
> +    line-height: 2.81;
Прибери  line-height: 2.81 
І задай маржинами відступ, ми вчора це обговорили, що прибераємо всі  line-height, окрім того що на body

2021-05-18 08:13 UTC, grytsayo commented on src/sass/_about-us.scss
> +    line-height: 2.81;
та я памятаю, але він мене дуже влаштовував))
ок

2021-05-18 08:24 UTC, ohrimovich approved these changes

2021-05-18 08:24 UTC, merged