Feature/about us
ohrimovich/donut-masterclass pull request #3
Opened 2021-05-13 20:08 UTC by grytsayo

Just for test

2021-05-13 21:09 UTC, ohrimovich requested changes

2021-05-13 21:09 UTC, ohrimovich commented on src/partials/about-us.html
> +        <!-- <picture>
Не вірний шлях до картинок ось так srset=''images/desktop/about-us_desktop.png'' і всі інші по аналогії

2021-05-13 21:09 UTC, ohrimovich commented on src/partials/about-us.html
> +        <div style="height:25px"></div>
Не вірно реалізований відступ
Краще задати about__title:not(:last-child)margin-bottom: 25px; в css
Це позбавить нас потреби задавати відступ для абзацу, після натискання кнопки read more

2021-05-13 21:09 UTC, ohrimovich commented on src/partials/about-us.html
> +        <button class="btn-more">
У кнопки відсутній атрибут type="button"

2021-05-13 21:09 UTC, ohrimovich commented on src/sass/_about-us.scss
> +    font-weight: normal;
font-weight задається числом
font-weight: 400;

2021-05-13 21:09 UTC, ohrimovich commented on src/sass/_about-us.scss
> +    font-weight: normal;
В даному випадку font-weight не потрібно задавати, ці стилі наслідуються з body

2021-05-13 21:09 UTC, ohrimovich commented on src/sass/_about-us.scss
> +    font-weight: normal;
font-weight задається числом
font-weight: 400;

2021-05-14 04:47 UTC, grytsayo commented on src/partials/about-us.html
> +        <!-- <picture>
srset=''images/desktop/about-us_desktop.png''   малось на увазі  srcset=?

2021-05-14 04:55 UTC, grytsayo commented on src/partials/about-us.html
> +        <div style="height:25px"></div>
:not(:last-child)margin-bottom: 25px не працює. Я власне із-за того укав інший спосіб

2021-05-14 07:21 UTC, ohrimovich commented on src/partials/about-us.html
> +        <!-- <picture>
Так, я там помилився

2021-05-14 07:22 UTC, ohrimovich commented on src/partials/about-us.html
> +        <div style="height:25px"></div>
Повинно працювати, скинь в комент код ситлів

2021-05-14 08:11 UTC, ohrimovich commented on src/partials/about-us.html
> +        <div style="height:25px"></div>
Можеш додати p в ul і тоді, все запрацює

2021-05-14 18:39 UTC, ohrimovich approved these changes

2021-05-14 19:09 UTC, merged