About desktop
ohrimovich/donut-masterclass pull request #8
Opened 2021-05-14 20:16 UTC by grytsayo

Desktop layout done

2021-05-15 12:40 UTC, grytsayo commented
It seems work more or less)

2021-05-15 13:48 UTC, ohrimovich requested changes

2021-05-15 13:48 UTC, ohrimovich commented on src/partials/about-us.html
> +            btnText.innerHTML = "Read less";
По шаблону кнопка less

2021-05-15 13:48 UTC, ohrimovich commented on src/sass/_about-us.scss
> +    max-width: 100%;
Ці стилі зайві
вони задані в _base.scss для тегу img

2021-05-16 09:07 UTC, ohrimovich approved these changes

2021-05-16 09:07 UTC, merged